import EnergyLensFeed, { type EnergyEvent } from "@/components/EnergyLensFeed";

export default function EnergyPage() {
  // Expanded to ~100 events for comprehensive intelligence feed
  const events: EnergyEvent[] = [
    {
      id: "1",
      title: "US Inflation Reduction Act - Clean Energy Credit Extension",
      date: "2025-11-08",
      sector: "renewables",
      impact: "high",
      description: "Treasury issues final regulations extending production tax credits for offshore wind projects through 2035.",
      commodityContext: "Offshore wind development accelerating; installed capacity projected to reach 30 GW by 2030.",
      taxImplications: [
        "Enhanced PTC rates of $27.5/MWh available for projects meeting prevailing wage requirements",
        "Direct pay election available for tax-exempt entities through 2032",
        "Energy storage add-on qualification extends ITC benefits",
      ],
    },
    {
      id: "2",
      title: "EU Carbon Border Adjustment Mechanism (CBAM) Reporting Begins",
      date: "2025-10-30",
      sector: "upstream",
      impact: "high",
      description: "First quarterly CBAM reports due for importers of crude oil and refined products into EU.",
      commodityContext: "Brent crude at $82/bbl; carbon pricing differential creating $8-12/bbl cost impact on non-EU imports.",
      taxImplications: [
        "Embedded emissions reporting required for all crude imports from non-EU sources",
        "CBAM certificates pricing at €85/tonne CO2, creating material cost increase",
        "Transfer pricing implications for intercompany crude purchases",
      ],
    },
    {
      id: "3",
      title: "India GST Rate Changes for Petroleum Products",
      date: "2025-10-22",
      sector: "downstream",
      impact: "medium",
      description: "GST Council proposes bringing natural gas under GST regime at 12% rate, effective April 2026.",
      taxImplications: [
        "Input tax credit availability will reduce cascading tax effect",
        "Petroleum products remain outside GST for now",
        "State VAT implications require separate analysis",
      ],
    },
    {
      id: "4",
      title: "UK Windfall Tax Extension Proposed",
      date: "2025-11-05",
      sector: "upstream",
      impact: "high",
      description: "Energy Profits Levy extended through 2030 with increased rate from 35% to 38%.",
      commodityContext: "North Sea production declining; oil at $80/bbl makes incremental projects economically marginal.",
      taxImplications: [
        "Effective combined tax rate on UK upstream profits now 78%",
        "Investment allowance reduced from 80% to 66%",
        "Decommissioning tax relief timing accelerated",
      ],
    },
    {
      id: "5",
      title: "China Carbon Trading Market Expansion",
      date: "2025-11-01",
      sector: "power",
      impact: "medium",
      description: "National ETS expands to include petrochemical and steel sectors effective 2026.",
      commodityContext: "Carbon allowance prices stable at ¥80/tonne; expected to increase with expanded coverage.",
      taxImplications: [
        "Carbon costs will be deductible for income tax purposes",
        "Transfer pricing implications for intercompany carbon allowance transfers",
        "Potential for carbon tax credits in certain provinces",
      ],
    },
    {
      id: "6",
      title: "Germany Hydrogen Tax Incentive Package",
      date: "2025-10-28",
      sector: "renewables",
      impact: "high",
      description: "New tax credits for green hydrogen production and distribution infrastructure investment.",
      taxImplications: [
        "Investment tax credit of 40% for electrolysis capacity installation",
        "Enhanced depreciation rates for hydrogen distribution assets",
        "VAT exemption for green hydrogen sales to industrial users",
      ],
    },
    {
      id: "7",
      title: "France Petroleum Products Excise Duty Increase",
      date: "2025-10-25",
      sector: "midstream",
      impact: "medium",
      description: "Excise duty on diesel and gasoline to increase by 5% effective January 2026.",
      taxImplications: [
        "Retail price impact estimated at €0.08/liter",
        "Transfer pricing benchmarking affected for petroleum product distribution",
        "Biofuel blend exemptions expanded to 15% content",
      ],
    },
    {
      id: "8",
      title: "Brazil Fuel Tax Reform Advances",
      date: "2025-10-20",
      sector: "downstream",
      impact: "medium",
      description: "Constitutional amendment proposal to unify state-level ICMS taxes on fuels.",
      taxImplications: [
        "Single nationwide ICMS rate would reduce compliance complexity",
        "Potential revenue impact to certain states creating transition challenges",
        "Federal compensation mechanism under discussion",
      ],
    },
    {
      id: "9",
      title: "Norway Petroleum Tax Credit Scheme Extended",
      date: "2025-10-18",
      sector: "upstream",
      impact: "high",
      description: "Temporary uplift for new field development extended through 2027.",
      commodityContext: "North Sea oil at $78/bbl; Norwegian production holding steady at 1.7 million bpd.",
      taxImplications: [
        "24% uplift on development costs continues to 2027",
        "78% marginal tax rate on upstream profits unchanged",
        "Immediate expensing of exploration costs maintained",
      ],
    },
    {
      id: "10",
      title: "Australia LNG Export Levy Proposed",
      date: "2025-10-15",
      sector: "midstream",
      impact: "high",
      description: "New federal levy on LNG exports proposed at 10% of free-on-board value.",
      commodityContext: "Asian LNG spot prices at $14/MMBtu; Australia is world's largest LNG exporter.",
      taxImplications: [
        "Estimated $2.5B annual revenue impact on major exporters",
        "Deductibility for income tax purposes under review",
        "Industry warning of project investment chilling effect",
      ],
    },
    {
      id: "11",
      title: "Canada Clean Fuel Regulations Phase 2",
      date: "2025-10-12",
      sector: "downstream",
      impact: "medium",
      description: "Carbon intensity reduction requirements increase to 12% by 2030.",
      taxImplications: [
        "Compliance credit trading creates new tax basis tracking requirements",
        "Blending incentives available for renewable diesel and SAF",
        "Provincial carbon tax integration requires coordination",
      ],
    },
    {
      id: "12",
      title: "UAE Corporate Tax Implementation - Energy Sector",
      date: "2025-10-10",
      sector: "upstream",
      impact: "high",
      description: "Federal corporate tax at 9% becomes effective; exemption for upstream oil/gas confirmed.",
      taxImplications: [
        "Upstream extraction activities remain under Emirate-level taxation",
        "Midstream and downstream operations subject to 9% federal tax",
        "Transfer pricing documentation requirements introduced",
      ],
    },
    {
      id: "13",
      title: "Mexico Energy Reform Tax Changes",
      date: "2025-10-08",
      sector: "power",
      impact: "medium",
      description: "New royalty structure for private power generation using natural gas.",
      taxImplications: [
        "5% royalty on gross power sales from gas-fired plants",
        "Exemption for combined-cycle plants with >55% efficiency",
        "VAT treatment clarification for wheeling charges",
      ],
    },
    {
      id: "14",
      title: "Indonesia B40 Biodiesel Mandate Delayed",
      date: "2025-10-05",
      sector: "downstream",
      impact: "low",
      description: "Implementation of 40% palm oil blend requirement postponed to 2027.",
      taxImplications: [
        "Biodiesel subsidy program remains in place at current levels",
        "Import duty structure on fossil diesel unchanged for now",
        "Replanting fund levy on CPO continues at 3%",
      ],
    },
    {
      id: "15",
      title: "Saudi Arabia VAT Increase Reversal Confirmed",
      date: "2025-10-01",
      sector: "downstream",
      impact: "medium",
      description: "VAT rate to decrease from 15% back to 5% on petroleum products effective Jan 2026.",
      taxImplications: [
        "Retail price reduction expected to boost consumption",
        "Input VAT credit adjustments required for inventory on hand",
        "Transition period guidance awaited from GAZT",
      ],
    },
    {
      id: "16",
      title: "Nigeria Petroleum Industry Act (PIA) Amendments",
      date: "2025-09-28",
      sector: "upstream",
      impact: "high",
      description: "Proposed amendments to royalty rates for deepwater production.",
      commodityContext: "Brent crude at $85/bbl; Nigerian production recovering to 1.5 million bpd.",
      taxImplications: [
        "Deepwater royalty rates proposed to decrease from 10% to 7.5%",
        "Hydrocarbon tax remains at 50% for offshore operations",
        "Gas flaring penalties increased significantly",
      ],
    },
    {
      id: "17",
      title: "Japan Carbon Pricing Mechanism Launch",
      date: "2025-09-25",
      sector: "power",
      impact: "high",
      description: "Fossil fuel levy introduced at ¥289/tonne CO2 for power generation.",
      taxImplications: [
        "Applies to coal, oil, and LNG-fired power generation",
        "Revenue recycling through renewable energy subsidies",
        "Corporate tax credit available for emissions reduction investments",
      ],
    },
    {
      id: "18",
      title: "South Korea Offshore Wind Tax Breaks",
      date: "2025-09-22",
      sector: "renewables",
      impact: "medium",
      description: "New tax incentives for offshore wind farm development announced.",
      taxImplications: [
        "10-year corporate tax holiday for qualifying projects",
        "Accelerated depreciation for offshore wind assets",
        "Import duty waiver on specialized installation vessels",
      ],
    },
    {
      id: "19",
      title: "Argentina Vaca Muerta Shale Tax Regime",
      date: "2025-09-20",
      sector: "upstream",
      impact: "high",
      description: "Special tax incentives for unconventional oil and gas development extended.",
      commodityContext: "Vaca Muerta production reaching 500k bpd; WTI at $76/bbl.",
      taxImplications: [
        "Income tax rate reduced to 25% (from 35%) for new wells",
        "Export tax exemption for incremental production",
        "Royalty rate capped at 12% vs standard 18%",
      ],
    },
    {
      id: "20",
      title: "Egypt Gas Export Tax Clarification",
      date: "2025-09-18",
      sector: "midstream",
      impact: "medium",
      description: "Ministry of Finance clarifies tax treatment of LNG export contracts.",
      taxImplications: [
        "Withholding tax rate of 5% confirmed for foreign partners",
        "Transfer pricing benchmarking required for intercompany gas sales",
        "Sovereign guarantee exemption from certain taxes maintained",
      ],
    },
    {
      id: "21",
      title: "Thailand Floating Solar PV Incentives",
      date: "2025-09-15",
      sector: "renewables",
      impact: "low",
      description: "BOI announces enhanced tax incentives for floating solar installations.",
      taxImplications: [
        "8-year corporate tax exemption for projects >50 MW",
        "Machinery import duty exemption",
        "Accelerated depreciation over 5 years vs standard 20",
      ],
    },
    {
      id: "22",
      title: "Vietnam Coal Tax Environmental Surcharge",
      date: "2025-09-12",
      sector: "power",
      impact: "medium",
      description: "New environmental protection tax on coal-fired power generation.",
      taxImplications: [
        "VND 50,000/tonne coal consumed for power generation",
        "Revenue earmarked for renewable energy transition fund",
        "Compliance reporting required quarterly",
      ],
    },
    {
      id: "23",
      title: "Colombia Oil Royalty Rate Increase",
      date: "2025-09-10",
      sector: "upstream",
      impact: "high",
      description: "Variable royalty rate increases for production above 5,000 bpd.",
      commodityContext: "Brent crude at $83/bbl; Colombian production at 770k bpd.",
      taxImplications: [
        "Royalty rate increases from 8% to 15% for production >100k bpd",
        "Sliding scale based on production volume and oil price",
        "Existing contracts grandfathered under old regime",
      ],
    },
    {
      id: "24",
      title: "Malaysia PETRONAS Cost Recovery Audit",
      date: "2025-09-08",
      sector: "upstream",
      impact: "medium",
      description: "Tax authority initiates comprehensive audit of PSC cost recovery claims.",
      taxImplications: [
        "Focus on overhead allocation and intercompany charges",
        "Transfer pricing documentation gaps identified",
        "Potential assessment of additional petroleum income tax",
      ],
    },
    {
      id: "25",
      title: "Spain Renewable Energy Tax Credit Expansion",
      date: "2025-09-05",
      sector: "renewables",
      impact: "medium",
      description: "Tax credits expanded to include battery storage and green hydrogen.",
      taxImplications: [
        "30% investment tax credit for qualifying storage projects",
        "Corporate tax deduction for green hydrogen R&D",
        "Accelerated depreciation for solar-plus-storage installations",
      ],
    },
    {
      id: "26",
      title: "Kazakhstan Subsoil Use Tax Reform",
      date: "2025-09-01",
      sector: "upstream",
      impact: "high",
      description: "New tax code introduces production-based taxation for oil fields.",
      taxImplications: [
        "Shift from excess profit tax to production tax",
        "Rate structure: 5-15% based on production volume",
        "Transition provisions for existing projects",
      ],
    },
    {
      id: "27",
      title: "Singapore Bunker Fuel Tax Adjustment",
      date: "2025-08-28",
      sector: "midstream",
      impact: "low",
      description: "Excise duty on marine fuel adjusted to align with carbon pricing.",
      taxImplications: [
        "Duty increase of SGD 5/tonne for high-sulfur fuel oil",
        "Low-sulfur fuel oil duty unchanged",
        "LNG bunker fuel maintains zero excise duty",
      ],
    },
    {
      id: "28",
      title: "Chile Lithium Royalty for Battery Production",
      date: "2025-08-25",
      sector: "renewables",
      impact: "medium",
      description: "New royalty on lithium extraction for battery manufacturing.",
      taxImplications: [
        "1% ad valorem royalty on lithium carbonate production",
        "Revenue dedicated to renewable energy infrastructure",
        "Existing mining contracts subject to renegotiation",
      ],
    },
    {
      id: "29",
      title: "Turkey Natural Gas Import Tax Reduction",
      date: "2025-08-22",
      sector: "midstream",
      impact: "medium",
      description: "VAT on natural gas imports reduced from 18% to 8%.",
      taxImplications: [
        "Aimed at reducing power generation costs",
        "Import duty on LNG remains at 0%",
        "Domestic production VAT treatment unchanged",
      ],
    },
    {
      id: "30",
      title: "Qatar LNG Long-Term Contract Tax Certainty",
      date: "2025-08-20",
      sector: "midstream",
      impact: "low",
      description: "Tax authority confirms stable tax regime for 25-year LNG contracts.",
      taxImplications: [
        "Corporate tax rate locked at 10% for contract duration",
        "Withholding tax exemption for foreign partners",
        "Transfer pricing safe harbor for LNG pricing",
      ],
    },
    {
      id: "31",
      title: "Poland Coal Phase-Out Tax Incentives",
      date: "2025-08-18",
      sector: "power",
      impact: "high",
      description: "Tax credits for early closure of coal-fired power plants.",
      taxImplications: [
        "One-time corporate tax credit equal to 50% of decommissioning costs",
        "Property tax exemption for 10 years on remediated sites",
        "Employee transition support costs fully deductible",
      ],
    },
    {
      id: "32",
      title: "Philippines Renewable Portfolio Standard Tax",
      date: "2025-08-15",
      sector: "renewables",
      impact: "medium",
      description: "New compliance fee for distribution utilities missing RPS targets.",
      taxImplications: [
        "PHP 0.50/kWh shortfall penalty",
        "Revenue funds renewable energy market development",
        "Renewable energy certificates tax treatment clarified",
      ],
    },
    {
      id: "33",
      title: "Israel Natural Gas Royalty Adjustment",
      date: "2025-08-12",
      sector: "upstream",
      impact: "medium",
      description: "Royalty rate on offshore gas production revised upward.",
      taxImplications: [
        "Royalty increases from 12.5% to 15% for new discoveries",
        "Existing fields grandfathered at current rates",
        "Profit levy remains at 20-50% based on R-factor",
      ],
    },
    {
      id: "34",
      title: "Denmark Wind Power Tax Credit Expansion",
      date: "2025-08-10",
      sector: "renewables",
      impact: "medium",
      description: "Enhanced tax credits for offshore wind projects in Baltic Sea.",
      taxImplications: [
        "Corporate tax exemption for first 10 years of operation",
        "Accelerated depreciation over 7 years",
        "VAT refund for construction phase expenses",
      ],
    },
    {
      id: "35",
      title: "Angola Marginal Field Development Incentives",
      date: "2025-08-08",
      sector: "upstream",
      impact: "high",
      description: "Tax incentives introduced for development of marginal oil fields.",
      commodityContext: "Brent at $81/bbl; Angola production declining to 1.1 million bpd.",
      taxImplications: [
        "Income tax holiday for first 5 years of production",
        "Surface tax exemption for marginal fields",
        "Simplified cost recovery procedures",
      ],
    },
    {
      id: "36",
      title: "Pakistan Gas Infrastructure Cess",
      date: "2025-08-05",
      sector: "midstream",
      impact: "medium",
      description: "New infrastructure development cess on natural gas transmission.",
      taxImplications: [
        "Rs 20/MMBTU levy on all gas transported through pipelines",
        "Revenue dedicated to pipeline expansion projects",
        "GST treatment as pass-through cost confirmed",
      ],
    },
    {
      id: "37",
      title: "Netherlands Windfall Profit Tax Extension",
      date: "2025-08-01",
      sector: "power",
      impact: "high",
      description: "Temporary windfall profit tax on electricity generation extended to 2026.",
      taxImplications: [
        "33% tax on electricity revenue above €180/MWh",
        "Renewable energy exemption maintained",
        "Quarterly payment obligations",
      ],
    },
    {
      id: "38",
      title: "Oman Crude Oil Export Tax Proposal",
      date: "2025-07-28",
      sector: "upstream",
      impact: "high",
      description: "Government considers export tax on crude oil to encourage domestic refining.",
      commodityContext: "Oman crude at $78/bbl; domestic refining capacity at 60% utilization.",
      taxImplications: [
        "Proposed 5% export tax on crude oil shipments",
        "Exemption for condensate and NGL exports",
        "Refined products export tax relief",
      ],
    },
    {
      id: "39",
      title: "Peru Mining Royalty Applied to Oil",
      date: "2025-07-25",
      sector: "upstream",
      impact: "medium",
      description: "Modified mining royalty regime extended to petroleum extraction.",
      taxImplications: [
        "1-12% sliding scale based on operating margin",
        "Additional special mining tax at 2-8.4% of operating profit",
        "Existing petroleum contracts require amendment",
      ],
    },
    {
      id: "40",
      title: "Bangladesh Solar Rooftop VAT Exemption",
      date: "2025-07-22",
      sector: "renewables",
      impact: "low",
      description: "VAT exemption extended to residential solar rooftop installations.",
      taxImplications: [
        "Full VAT exemption on system components and installation",
        "Income tax credit for homeowners equal to 15% of system cost",
        "Commercial installations continue to pay standard VAT",
      ],
    },
    {
      id: "41",
      title: "Greece Renewable Energy Solidarity Contribution",
      date: "2025-07-20",
      sector: "renewables",
      impact: "medium",
      description: "Special levy on renewable energy revenues above certain thresholds.",
      taxImplications: [
        "90% tax on revenue exceeding €130/MWh",
        "Applies to wind and solar projects",
        "Temporary measure through 2025",
      ],
    },
    {
      id: "42",
      title: "Russia Oil Export Duty Formula Change",
      date: "2025-07-18",
      sector: "upstream",
      impact: "high",
      description: "Export duty calculation methodology revised to capture higher prices.",
      commodityContext: "Urals crude discount to Brent narrowing; trading at $75/bbl.",
      taxImplications: [
        "Export duty increases from $15/bbl to $22/bbl at current prices",
        "Mineral extraction tax coordination adjusted",
        "Net effective tax rate on upstream operations now ~65%",
      ],
    },
    {
      id: "43",
      title: "South Africa Carbon Tax Rate Increase",
      date: "2025-07-15",
      sector: "power",
      impact: "high",
      description: "Carbon tax rate increases from R159 to R190 per tonne CO2.",
      taxImplications: [
        "Significant impact on coal-fired power generation costs",
        "Free allowances reduced from 95% to 90%",
        "Revenue recycling through renewable energy programs",
      ],
    },
    {
      id: "44",
      title: "Taiwan Offshore Wind Localization Tax Credits",
      date: "2025-07-12",
      sector: "renewables",
      impact: "medium",
      description: "Enhanced tax incentives for local manufacturing of wind components.",
      taxImplications: [
        "Corporate tax credit of 25% for qualifying local manufacturing",
        "Import duty waiver contingent on 60% local content",
        "R&D tax credit doubled for offshore wind technology",
      ],
    },
    {
      id: "45",
      title: "Mozambique LNG Project Tax Exemptions",
      date: "2025-07-10",
      sector: "midstream",
      impact: "high",
      description: "Government grants additional tax exemptions to revive Area 1 LNG project.",
      taxImplications: [
        "VAT exemption on all construction equipment and materials",
        "Corporate income tax holiday extended to 15 years",
        "Withholding tax exemption for foreign contractor payments",
      ],
    },
    {
      id: "46",
      title: "New Zealand ETS Carbon Price Floor",
      date: "2025-07-08",
      sector: "power",
      impact: "medium",
      description: "Emissions Trading Scheme introduces price floor of NZD 60/tonne.",
      taxImplications: [
        "Provides certainty for long-term investment decisions",
        "Increases cost for fossil fuel power generation",
        "Revenue impact on carbon-intensive industries",
      ],
    },
    {
      id: "47",
      title: "Iraq Gas Flaring Penalty Enhancement",
      date: "2025-07-05",
      sector: "upstream",
      impact: "medium",
      description: "Penalties for gas flaring increased substantially to encourage utilization.",
      taxImplications: [
        "Flaring penalty increases from $2/MCF to $5/MCF",
        "Tax deductibility of penalties eliminated",
        "Investment credit available for gas capture infrastructure",
      ],
    },
    {
      id: "48",
      title: "Belgium Nuclear Phase-Out Tax Adjustments",
      date: "2025-07-01",
      sector: "power",
      impact: "high",
      description: "Nuclear levy adjusted as Belgium plans reactor closures.",
      taxImplications: [
        "Annual nuclear levy reduced from €550M to €300M",
        "Decommissioning fund contributions tax deductible",
        "Replacement capacity investment tax credits introduced",
      ],
    },
    {
      id: "49",
      title: "Trinidad & Tobago Supplemental Petroleum Tax",
      date: "2025-06-28",
      sector: "upstream",
      impact: "high",
      description: "Supplemental petroleum tax rate structure revised based on oil prices.",
      commodityContext: "WTI at $77/bbl; T&T production stable at 60k bpd.",
      taxImplications: [
        "SPT rate increases to 30% when prices exceed $75/bbl",
        "Previous 25% rate applies for $50-75/bbl range",
        "Quarterly payment and reconciliation required",
      ],
    },
    {
      id: "50",
      title: "Austria Renewable Heat Tax Incentives",
      date: "2025-06-25",
      sector: "renewables",
      impact: "low",
      description: "New tax credits for biomass and geothermal heating systems.",
      taxImplications: [
        "Investment tax credit of 35% for qualifying systems",
        "Accelerated depreciation over 5 years",
        "VAT reduction from 20% to 10% on installations",
      ],
    },
    {
      id: "51",
      title: "Kuwait Crude Export Subsidy Removal",
      date: "2025-06-22",
      sector: "upstream",
      impact: "medium",
      description: "Government eliminates domestic crude oil price subsidy for refineries.",
      taxImplications: [
        "Refineries to pay international market price minus transport differential",
        "Corporate tax implications for refining margins",
        "Potential retail price increases downstream",
      ],
    },
    {
      id: "52",
      title: "Ecuador Oil Export Tax Reduction",
      date: "2025-06-20",
      sector: "upstream",
      impact: "medium",
      description: "Export tax on crude oil reduced to attract investment.",
      commodityContext: "Oriente crude at $68/bbl; Ecuador production at 485k bpd.",
      taxImplications: [
        "Export tax reduced from 5% to 2.5%",
        "Applies to production above 400k bpd threshold",
        "Income tax rate remains at 25% for petroleum sector",
      ],
    },
    {
      id: "53",
      title: "Romania Wind Energy Feed-in Tariff Tax Treatment",
      date: "2025-06-18",
      sector: "renewables",
      impact: "low",
      description: "Tax authority clarifies income recognition for green certificate system.",
      taxImplications: [
        "Revenue from green certificate sales taxable when realized",
        "Mark-to-market accounting not required for certificate inventory",
        "Trading losses fully deductible against other income",
      ],
    },
    {
      id: "54",
      title: "Libya Production Sharing Agreement Tax Terms",
      date: "2025-06-15",
      sector: "upstream",
      impact: "high",
      description: "New PSA model introduced with revised tax and royalty structure.",
      taxImplications: [
        "Royalty rate: 16.67% of gross production",
        "Cost oil limited to 40% of production",
        "Profit oil split: 65-85% to NOC depending on production levels",
      ],
    },
    {
      id: "55",
      title: "Ireland Data Center Energy Tax",
      date: "2025-06-12",
      sector: "power",
      impact: "medium",
      description: "New levy on electricity consumption by data centers proposed.",
      taxImplications: [
        "€10/MWh levy on data center electricity consumption",
        "Revenue to fund renewable energy grid infrastructure",
        "Renewable energy direct purchases exempt from levy",
      ],
    },
    {
      id: "56",
      title: "Venezuela Oil Sector Tax Amnesty",
      date: "2025-06-10",
      sector: "upstream",
      impact: "medium",
      description: "Government offers tax debt forgiveness program for oil companies.",
      taxImplications: [
        "Penalty and interest waivers on unpaid petroleum taxes",
        "Principal amounts payable over 5 years at 0% interest",
        "Requirement to resume normal operations and production",
      ],
    },
    {
      id: "57",
      title: "Hungary Solar Farm Property Tax Exemption",
      date: "2025-06-08",
      sector: "renewables",
      impact: "low",
      description: "Property tax exemption introduced for utility-scale solar installations.",
      taxImplications: [
        "Full exemption from local property tax for 15 years",
        "Applies to projects commissioned after Jan 1, 2025",
        "Agricultural land use tax remains applicable",
      ],
    },
    {
      id: "58",
      title: "Algeria Hydrocarbon Tax Code Revision",
      date: "2025-06-05",
      sector: "upstream",
      impact: "high",
      description: "Comprehensive reform of petroleum fiscal regime to attract investment.",
      commodityContext: "Brent at $80/bbl; Algeria production declining to 900k bpd.",
      taxImplications: [
        "Profit tax reduced from 70% to 50-65% based on field size",
        "Royalty rates: 10-15% sliding scale",
        "Cost recovery ceiling increased to 50%",
      ],
    },
    {
      id: "59",
      title: "Cyprus Marine Fuel Bunker Tax",
      date: "2025-06-01",
      sector: "midstream",
      impact: "low",
      description: "New excise duty on marine fuel bunker sales.",
      taxImplications: [
        "€2/tonne excise duty on all bunker fuel sales",
        "Revenue dedicated to port infrastructure development",
        "Competitive concerns raised by shipping industry",
      ],
    },
    {
      id: "60",
      title: "Bolivia Natural Gas Export Royalty Increase",
      date: "2025-05-28",
      sector: "midstream",
      impact: "medium",
      description: "Export royalty on natural gas to Argentina and Brazil increased.",
      taxImplications: [
        "Royalty rate increases from 18% to 22%",
        "Domestic sales royalty remains at 18%",
        "Department-level royalty shares adjusted",
      ],
    },
    {
      id: "61",
      title: "Serbia Renewable Energy Auction Tax Treatment",
      date: "2025-05-25",
      sector: "renewables",
      impact: "low",
      description: "Tax incentives clarified for renewable energy auction winners.",
      taxImplications: [
        "Corporate tax rate reduced to 10% (from 15%) for auction projects",
        "Accelerated depreciation over 8 years",
        "Import duty exemption for equipment not available domestically",
      ],
    },
    {
      id: "62",
      title: "Azerbaijan Shah Deniz Tax Stability",
      date: "2025-05-22",
      sector: "upstream",
      impact: "medium",
      description: "Tax stability agreement confirmed for Shah Deniz gas field expansion.",
      taxImplications: [
        "PSA terms locked through 2050",
        "Profit gas split: 75% to consortium, 25% to SOCAR",
        "Exemption from future tax increases confirmed",
      ],
    },
    {
      id: "63",
      title: "Morocco Solar CSP Investment Incentives",
      date: "2025-05-20",
      sector: "renewables",
      impact: "medium",
      description: "Enhanced tax incentives for concentrated solar power projects.",
      taxImplications: [
        "5-year corporate tax exemption for CSP projects >100 MW",
        "VAT exemption on imported equipment and materials",
        "Customs duty waiver for specialized components",
      ],
    },
    {
      id: "64",
      title: "Ghana Petroleum Revenue Management",
      date: "2025-05-18",
      sector: "upstream",
      impact: "medium",
      description: "New petroleum revenue allocation framework affects carried interest.",
      taxImplications: [
        "GNPC carried interest increased from 10% to 15%",
        "Additional oil entitlement to government at high prices",
        "Contractor share of profit oil reduced proportionally",
      ],
    },
    {
      id: "65",
      title: "Portugal Wave Energy Tax Credits",
      date: "2025-05-15",
      sector: "renewables",
      impact: "low",
      description: "New tax incentives for wave and tidal energy projects.",
      taxImplications: [
        "Investment tax credit of 30% for demonstration projects",
        "R&D super-deduction at 150% for ocean energy technology",
        "Property tax exemption for first 10 years",
      ],
    },
    {
      id: "66",
      title: "Turkmenistan Gas Transit Tax Waiver",
      date: "2025-05-12",
      sector: "midstream",
      impact: "low",
      description: "Transit tax waiver for natural gas pipelines to Afghanistan.",
      taxImplications: [
        "Transit fee exemption for TAPI pipeline volumes",
        "Applies to first 33 BCM per year",
        "Standard transit taxes apply to additional volumes",
      ],
    },
    {
      id: "67",
      title: "Kenya Geothermal Development Levy",
      date: "2025-05-10",
      sector: "renewables",
      impact: "low",
      description: "New levy on geothermal electricity generation to fund exploration.",
      taxImplications: [
        "KES 0.05/kWh levy on geothermal power generation",
        "Revenue dedicated to geothermal exploration fund",
        "Capped at 2% of project revenue",
      ],
    },
    {
      id: "68",
      title: "Jordan Oil Shale Royalty Framework",
      date: "2025-05-08",
      sector: "upstream",
      impact: "medium",
      description: "Royalty structure established for oil shale extraction projects.",
      taxImplications: [
        "Royalty rate: 5% of gross revenue from oil shale",
        "Income tax rate: 24% of net profits",
        "Equipment import duty exemption for first 5 years",
      ],
    },
    {
      id: "69",
      title: "Panama Bunker Fuel Tax Alignment",
      date: "2025-05-05",
      sector: "midstream",
      impact: "low",
      description: "Bunker fuel excise tax aligned with regional rates.",
      taxImplications: [
        "Excise tax reduced from $0.05/gallon to $0.02/gallon",
        "Maintains competitiveness with Caribbean bunkering hubs",
        "VAT treatment unchanged at 7%",
      ],
    },
    {
      id: "70",
      title: "Uzbekistan Gas Processing Tax Holiday",
      date: "2025-05-01",
      sector: "midstream",
      impact: "medium",
      description: "Tax incentives for new gas processing and petrochemical facilities.",
      taxImplications: [
        "7-year corporate income tax holiday",
        "Property tax and land tax exemptions",
        "Customs duty waiver on imported process equipment",
      ],
    },
    {
      id: "71",
      title: "Iceland Geothermal Export Tax",
      date: "2025-04-28",
      sector: "renewables",
      impact: "low",
      description: "New tax on geothermal energy exported via submarine cables.",
      taxImplications: [
        "2% gross revenue tax on exported geothermal electricity",
        "Revenue to fund domestic energy infrastructure",
        "Domestic sales exempt from this tax",
      ],
    },
    {
      id: "72",
      title: "Tunisia Offshore Gas Development Incentives",
      date: "2025-04-25",
      sector: "upstream",
      impact: "medium",
      description: "Enhanced fiscal terms for offshore gas discoveries.",
      taxImplications: [
        "Royalty rate reduced to 8% for deepwater gas",
        "Cost recovery ceiling increased to 60%",
        "Profit gas split: 70% contractor, 30% government",
      ],
    },
    {
      id: "73",
      title: "Senegal First Oil Tax Regime Clarification",
      date: "2025-04-22",
      sector: "upstream",
      impact: "high",
      description: "Tax treatment clarified ahead of Sangomar field first oil.",
      commodityContext: "Sangomar expected to produce 100k bpd; Brent at $82/bbl.",
      taxImplications: [
        "Corporate income tax: 30% of taxable profits",
        "Cost oil limited to 75% of production",
        "Royalty: 10% of gross production value",
      ],
    },
    {
      id: "74",
      title: "Croatia LNG Terminal Tax Exemption",
      date: "2025-04-20",
      sector: "midstream",
      impact: "low",
      description: "Tax exemptions extended for Krk LNG terminal expansion.",
      taxImplications: [
        "Property tax exemption for expansion phase",
        "VAT exemption on construction costs",
        "Corporate income tax rate reduced to 10% for terminal operator",
      ],
    },
    {
      id: "75",
      title: "Ghana Local Content Tax Compliance",
      date: "2025-04-18",
      sector: "upstream",
      impact: "medium",
      description: "Enhanced penalties for non-compliance with local content requirements.",
      taxImplications: [
        "Penalty of 10% of contract value for non-compliant procurement",
        "Tax deductibility denied for non-compliant local content costs",
        "Quarterly reporting requirements introduced",
      ],
    },
    {
      id: "76",
      title: "Estonia Shale Oil Sector Environmental Tax",
      date: "2025-04-15",
      sector: "upstream",
      impact: "medium",
      description: "Environmental tax on oil shale mining increased significantly.",
      taxImplications: [
        "Mining tax increases from €2.50 to €4.00 per tonne",
        "CO2 tax component added at €50/tonne",
        "Decommissioning fund contributions now tax deductible",
      ],
    },
    {
      id: "77",
      title: "Côte d'Ivoire Gas-to-Power Tax Incentives",
      date: "2025-04-12",
      sector: "power",
      impact: "medium",
      description: "Tax breaks for gas-fired power generation using domestic gas.",
      taxImplications: [
        "5-year corporate tax holiday for new gas power plants",
        "Accelerated depreciation over 6 years",
        "VAT exemption on natural gas fuel supply",
      ],
    },
    {
      id: "78",
      title: "Guyana Production Bonus Tax Treatment",
      date: "2025-04-10",
      sector: "upstream",
      impact: "medium",
      description: "Tax treatment clarified for production milestone bonuses.",
      commodityContext: "Guyana production exceeding 600k bpd; multiple FPSOs operating.",
      taxImplications: [
        "Production bonuses treated as government take, not taxable revenue",
        "Cost recovery adjustment to reflect bonus payments",
        "Profit oil split unaffected by bonus payments",
      ],
    },
    {
      id: "79",
      title: "Tanzania LNG Project Fiscal Terms",
      date: "2025-04-08",
      sector: "midstream",
      impact: "high",
      description: "Fiscal framework finalized for onshore LNG development.",
      taxImplications: [
        "Royalty: 12.5% of gross LNG sales revenue",
        "Corporate tax: 30% with 5-year loss carryforward",
        "VAT exemption for construction materials and equipment",
      ],
    },
    {
      id: "80",
      title: "Latvia Renewable Obligation Support Scheme",
      date: "2025-04-05",
      sector: "renewables",
      impact: "low",
      description: "Tax treatment of renewable obligation certificates clarified.",
      taxImplications: [
        "ROC revenue recognized when certificates issued",
        "Exempt from VAT when traded on secondary market",
        "Corporate tax deduction available for ROC purchase costs",
      ],
    },
    {
      id: "81",
      title: "Papua New Guinea LNG Expansion Tax Terms",
      date: "2025-04-01",
      sector: "midstream",
      impact: "high",
      description: "Additional fiscal stability for PNG LNG expansion project.",
      taxImplications: [
        "Tax stability locked through 2055 for expansion trains",
        "Corporate tax rate: 30% with development allowance",
        "Withholding tax: 10% on dividends to foreign shareholders",
      ],
    },
    {
      id: "82",
      title: "Myanmar Offshore Production Sharing Terms",
      date: "2025-03-28",
      sector: "upstream",
      impact: "medium",
      description: "Revised PSC model terms for offshore licensing round.",
      taxImplications: [
        "Royalty: 10% of gross production",
        "Cost recovery limited to 50% of production",
        "Commercial discovery bonus: $5M upon FID",
      ],
    },
    {
      id: "83",
      title: "Uruguay Wind Energy Export Tax Credit",
      date: "2025-03-25",
      sector: "renewables",
      impact: "low",
      description: "Tax credits for wind energy exported to Argentina and Brazil.",
      taxImplications: [
        "10% tax credit on revenue from cross-border electricity sales",
        "Enhanced credit of 15% for off-peak exports",
        "Domestic sales eligible for standard renewable incentives only",
      ],
    },
    {
      id: "84",
      title: "Cameroon Gas Monetization Tax Holiday",
      date: "2025-03-22",
      sector: "midstream",
      impact: "medium",
      description: "Tax incentives for stranded gas monetization projects.",
      taxImplications: [
        "10-year corporate tax holiday for gas processing plants",
        "Import duty exemption for LNG liquefaction equipment",
        "Accelerated capital allowances",
      ],
    },
    {
      id: "85",
      title: "Suriname Offshore Oil First Production",
      date: "2025-03-20",
      sector: "upstream",
      impact: "high",
      description: "Tax framework confirmed for Block 58 oil development.",
      taxImplications: [
        "PSC terms: 6.25% royalty on gross production",
        "Cost recovery cap: 75% of gross revenue",
        "Profit oil split: 52% contractor, 48% government",
      ],
    },
    {
      id: "86",
      title: "Mongolia Coal Export Royalty Adjustment",
      date: "2025-03-18",
      sector: "power",
      impact: "medium",
      description: "Royalty rates for coal exports to China revised.",
      taxImplications: [
        "Royalty increases from 5% to 7.5% of FOB value",
        "Applies to thermal and coking coal exports",
        "Domestic coal sales royalty unchanged at 2.5%",
      ],
    },
    {
      id: "87",
      title: "Bahrain Refined Products Export Incentive",
      date: "2025-03-15",
      sector: "downstream",
      impact: "low",
      description: "Tax credits introduced for petroleum product exports.",
      taxImplications: [
        "5% tax credit on export revenues for refined products",
        "Aimed at improving refinery competitiveness",
        "Crude oil exports excluded from incentive",
      ],
    },
    {
      id: "88",
      title: "Timor-Leste Greater Sunrise Tax Agreement",
      date: "2025-03-12",
      sector: "upstream",
      impact: "high",
      description: "Fiscal terms agreed for Greater Sunrise gas field development.",
      taxImplications: [
        "Revenue split: 70% Timor-Leste, 30% Australia",
        "Royalty: 10% of gross wellhead value",
        "Petroleum tax: 40% of taxable income",
      ],
    },
    {
      id: "89",
      title: "Madagascar Heavy Oil Development Incentives",
      date: "2025-03-10",
      sector: "upstream",
      impact: "medium",
      description: "Special fiscal regime for heavy oil and bitumen projects.",
      taxImplications: [
        "Reduced royalty of 8% vs standard 12%",
        "Enhanced cost recovery at 80% ceiling",
        "Corporate tax holiday for first 3 years of production",
      ],
    },
    {
      id: "90",
      title: "Sri Lanka Solar-Wind Hybrid Tax Benefits",
      date: "2025-03-08",
      sector: "renewables",
      impact: "low",
      description: "Additional tax incentives for hybrid renewable energy projects.",
      taxImplications: [
        "Corporate tax exemption extended to 12 years (from 8 years)",
        "Accelerated depreciation for energy storage component",
        "Import duty waiver on hybrid inverter systems",
      ],
    },
    {
      id: "91",
      title: "Cuba Renewable Energy Joint Venture Incentives",
      date: "2025-03-05",
      sector: "renewables",
      impact: "medium",
      description: "Tax incentives for foreign investment in renewable energy.",
      taxImplications: [
        "8-year corporate tax holiday",
        "Customs duty exemption for equipment imports",
        "Profit repatriation tax reduced to 5%",
      ],
    },
    {
      id: "92",
      title: "Namibia Orange Basin Exploration Tax Terms",
      date: "2025-03-01",
      sector: "upstream",
      impact: "high",
      description: "Favorable fiscal terms for offshore deepwater exploration.",
      taxImplications: [
        "Royalty: 5% for deepwater discoveries",
        "Cost recovery: up to 70% of production",
        "Corporate tax: 35% with ring-fencing provisions",
      ],
    },
    {
      id: "93",
      title: "Nicaragua Geothermal Concession Tax Relief",
      date: "2025-02-25",
      sector: "renewables",
      impact: "low",
      description: "Tax exemptions for geothermal power plant development.",
      taxImplications: [
        "10-year income tax exemption",
        "Import duty waiver for drilling and generation equipment",
        "Municipal tax exemptions during construction",
      ],
    },
    {
      id: "94",
      title: "Brunei Deepwater Gas Fiscal Incentives",
      date: "2025-02-22",
      sector: "upstream",
      impact: "medium",
      description: "Enhanced terms for deepwater gas development offshore Brunei.",
      taxImplications: [
        "Royalty reduced to 8% for water depths >1000m",
        "Cost recovery ceiling increased to 65%",
        "Ring-fence relief for deepwater projects",
      ],
    },
    {
      id: "95",
      title: "Zambia Solar Mini-Grid Tax Exemptions",
      date: "2025-02-20",
      sector: "renewables",
      impact: "low",
      description: "Tax breaks for rural solar mini-grid developments.",
      taxImplications: [
        "5-year corporate tax holiday for rural electrification projects",
        "VAT zero-rating for solar equipment",
        "Customs duty exemption on batteries and inverters",
      ],
    },
    {
      id: "96",
      title: "Lebanon Offshore Gas Royalty Rates",
      date: "2025-02-18",
      sector: "upstream",
      impact: "medium",
      description: "Royalty framework established for offshore gas blocks.",
      taxImplications: [
        "Royalty: 4-12% sliding scale based on production rates",
        "Corporate tax: 20% of net profits",
        "Signature and production bonuses defined",
      ],
    },
    {
      id: "97",
      title: "Honduras Wind Farm Property Tax Relief",
      date: "2025-02-15",
      sector: "renewables",
      impact: "low",
      description: "Property tax exemptions for wind energy projects.",
      taxImplications: [
        "15-year property tax exemption on wind farm land",
        "Equipment import duty waiver",
        "Corporate tax reduced to 10% (from 25%) for first 10 years",
      ],
    },
    {
      id: "98",
      title: "Yemen LNG Force Majeure Tax Implications",
      date: "2025-02-12",
      sector: "midstream",
      impact: "medium",
      description: "Tax treatment during LNG facility force majeure period.",
      taxImplications: [
        "Tax obligation suspension during force majeure",
        "No penalties for non-payment during suspension",
        "Royalty resumption upon restart of operations",
      ],
    },
    {
      id: "99",
      title: "Mauritius Offshore Wind Feasibility Incentives",
      date: "2025-02-10",
      sector: "renewables",
      impact: "low",
      description: "Tax credits for offshore wind feasibility studies.",
      taxImplications: [
        "50% tax credit for feasibility study costs",
        "Accelerated deduction for met-ocean monitoring expenses",
        "Customs duty exemption on survey equipment",
      ],
    },
    {
      id: "100",
      title: "Equatorial Guinea Gas Flaring Reduction Incentive",
      date: "2025-02-08",
      sector: "upstream",
      impact: "medium",
      description: "Tax credits for gas utilization infrastructure investment.",
      taxImplications: [
        "25% investment tax credit for gas gathering and processing",
        "Flaring penalty waivers for projects under development",
        "Accelerated depreciation for gas utilization assets",
      ],
    },
  ];

  return (
    <div className="h-full flex flex-col">
      <div className="p-6 border-b border-border">
        <h1 className="text-3xl font-bold" data-testid="text-page-title">Energy Lens Intelligence Feed</h1>
        <p className="text-muted-foreground mt-1">
          Tax developments filtered through energy sector perspective with commodity context • {events.length} alerts
        </p>
      </div>
      <div className="flex-1 p-6 overflow-auto">
        <EnergyLensFeed events={events} />
      </div>
    </div>
  );
}
